name: Deploy to Hetzner

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: root
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          cd /root/new_tbot
          git pull origin main
          /bin/systemctl restart bot.service
